### ISSUE TITLE
Error invalid status:'0'

### ISSUE THREAD

**Issue by Freako95** [tomicooler/UniverseSplitterUnofficial#1]
Error

Invalid status:'0'

After pressing the button to split the universe I get this error

**Comment by tomicooler** [comment]
Yesterday the The ANU Quantum Random Numbers Server was unavailable, probably that was the reason for this error message (the error message is not very user friendly).

Can you try it again, does it work for you now? Thanks.

**Comment by Freako95** [comment]
Indeed it works now. Thanks!
Does your app also have a roadmap with past decisions to see where you are now compared to what could have been?

**Comment by tomicooler** [comment]
Not yet, but there was already a request about that. So maybe later I will add that feature.

**Comment by Freako95** [comment]
Cool! I think it will add alot towards the app.
